# Configurations for the robot

# XML file location
robot_xml: "/home/zolkin/AmberLab/bilevel-gait-gen/models/a1_description/xml/a1.xml"

robot_urdf: "/home/zolkin/AmberLab/bilevel-gait-gen/models/a1_description/urdf/a1.urdf"

collision_frames: ["FL_foot", "FR_foot", "RL_foot", "RR_foot"]    # for pinocchio
collision_bodies: [4, 7, 10, 13]  # for mujoco
# these need to match ^

foot_type: "POINT_FEET"

## ----------------------- Configurations ----------------------- ##
# Note: All configs should match pinocchio!

# initial joint config
# xp, yp, zp, qw, qx, qy, qz, q0, ..., q11 - note that the angles are quaternions and need to be normalized
init_config: [0., 0., 0.3541, 0, 0, 0, 1.0, # -0.0004, 0.004, 0.0001,
              -0.02, 0.2, -0.977,       # front left
              0.02, 0.2, -0.977,        # front right
              0.08, 0.45, -1.03,        # rear left
              -0.08, 0.45, -1.03]       # rear right
#  [0., 0., 0.3341, 1., 0, 0, 0,
#              -0.02, 1.5, -1.75, # -0.976,     # front right
#              0.02, 0.2, -1.25, # -0.977,      # front left
#              -0.08, 0.2, -1.25, # -1.03,       # rear right
#              0.08, 1.5, -1.75] # -1.03]        # rear left
#init_config: [0., 0., 0.3541, 1., 0, 0, 0, # -0.0004, 0.004, 0.0001,
#              -0.02, 0.2, -0.977,     # front right
#              0.02, 0.524, -1.63,      # front left
#              -0.08, 0.498, -1.57,       # rear right
#              0.08, 0.45, -1.03]
# initial joint velocity
# xv, yv, zv, angle rates, v0, ..., v11
init_vel: [0., 0., 0., 0., 0., 0.,
           0., 0., 0.,
           0., 0., 0.,
           0., 0., 0.,
           0., 0., 0.]

#standing_config: [0., 0., 0.36, 1., 0., 0., 0.,
#                 -0.05, 0.2, -0.91,
#                 0.05, 0.2, -0.91,
#                 -0.0788, 0.6, -.91,
#                 0.0798, 0.6, -.91]

target_config: [0., 0., 0.3541, 0, 0, 0, 1.0,
                -0.02, -1, -0.977,     # front left
                0.02, 0.2, -0.977,     # front right
                0.08, 0.45, -1.03,     # rear left
                -0.08, 0.45, -1.03]    # rear right

standing_vel: [0., 0., 0., 0., 0., 0.,
               0., 0., 0.,
               0., 0., 0.,
               0., 0., 0.,
               0., 0., 0.]

## ----------------------- Low Level Controller ----------------------- ##
controller_type: "QP_CONTROL"   # or PD_GRAV_COMP
control_rate: 250  # Hz
torque_bounds: [100, 100, 100,
                 100, 100, 100,
                 100, 100, 100,
                 100, 100, 100] # 33.5
#  [100, 100, 100,
#   100, 100, 100,
#   100, 100, 100,
#   100, 100, 100]
friction_coef: 0.3

# TODO: Tune
base_pos_gains: [0, 0]  # kd_pos, kp_pos  need the kd~100 and kp~1000 and the torso having higher weight to override the legs significantly
base_ang_gains: [0, 0]  # kd_ang, kp_ang
kp_joint_gains: [0, 0, 0, 200, 200, 200, 200, 200, 200, 0, 0, 0]
kd_joint_gains: [0, 0, 0, 20, 20, 20, 20, 20, 20, 0, 0, 0]
# 400, 400, 0, 0, 400, 1000

leg_tracking_weight: 0.1
torso_tracking_weight: 10
force_tracking_weight: 0

## ----------------------- MPC ----------------------- ##
discretization_steps: 1
num_nodes: 50
integrator_dt: 0.015
num_qp: 1
#vel_bounds: [3, 3, 3,
#             3, 3, 3,
#             3, 3, 3,
#             3, 3, 3]
vel_bounds: [10, 10, 10,
             10, 10, 10,
             10, 10, 10,
             10, 10, 10]
joint_bounds_lb: [-0.802851, -1.0472, -2.69653,
                  -0.802851, -1.0472, -2.69653,
                  -0.802851, -1.0472, -2.69653,
                  -0.802851, -1.0472, -2.69653]
joint_bounds_ub:  [0.802851, 4.18879, -0.916298,
                  0.802851, 4.18879, -0.916298,
                  0.802851, 4.18879, -0.916298,
                  0.802851, 4.18879, -0.916298]

num_switches: 2
force_bound: 300

swing_height: 0.12

num_polys: 3

x_des: 2
y_des: 1

run_time_iterations: 200

foot_offset: 0.02

## --- Temp --- ##
viz_rate: 0.015