# Configurations for the robot

# XML file location
robot_xml: "/home/zolkin/AmberLab/bilevel-gait-gen/models/adam/adam.xml"
# note that the with feet model does not work right now and there are discrepencies between the URDF and the XML for that one.

robot_urdf: "/home/zolkin/AmberLab/bilevel-gait-gen/models/adam/adam.urdf"

collision_frames: ["left_foot", "right_foot"]    # for pinocchio
collision_bodies: [5, 9]  # for mujoco
# these need to match ^

foot_type: "POINT_FEET"   # other option: FLAT_FOOT

## ----------------------- Configurations ----------------------- ##
# initial joint config
# xp, yp, zp, qw, qx, qy, qz, q0, ..., q11 - note that the angles are quaternions and need to be normalized
init_config: [0., 0., 0.6844, 1., 0, 0, 0,
              0., 0., -0.4, 0.7,
              0., 0., -0.4, 0.7,
              0., 0., 0.,
              0., 0., 0.]

# initial joint velocity
# xv, yv, zv, angle rates, v0, ..., v11
init_vel: [0., 0., 0., 0., 0, 0,
           0., 0., 0., 0.,
           0., 0., 0., 0.,
           0., 0., 0.,
           0., 0., 0.]

standing_config: [0., 0., 0.6844, 1., 0, 0, 0,
                  0., 0., -0.4, 0.7,
                  0., 0., -0.4, 0.7,
                  0., 0., 0.,
                  0., 0., 0.]


standing_vel: [0., 0., 0., 0., 0, 0,
                0., 0., 0., 0.,
                0., 0., 0., 0.,
                0., 0., 0.,
                0., 0., 0.]

## ----------------------- Low Level Controller ----------------------- ##
control_rate: 400  # Hz

controller_type: "PD_GRAV_COMP" # QP_CONTROL

torque_bounds: [33.5, 33.5, 33.5, 33.5,
                33.5, 33.5, 33.5, 33.5,
                33.5, 33.5, 33.5,
                33.5, 33.5, 33.5]
friction_coef: 0.3
base_pos_gains: [12, 100]  # kd_pos, kp_pos  need the kd~100 and kp~1000 and the torso having higher weight to override the legs significantly
base_ang_gains: [12, 100]  # kd_ang, kp_ang
joint_gains: [20, 200]     # I can get these pretty high without getting close to the torque bounds

leg_tracking_weight: 100
torso_tracking_weight: 10
force_tracking_weight: 1